xpath1 = ['/div[3]/button[1]','/div[2]/div[3]/button[1]','/div[1]/div[2]/div[3]/button[1]',
'/section[1]/div[1]/div[2]/div[3]/button[1]',
'/div[1]/section[1]/div[1]/div[2]/div[3]/button[1]',
'/div[1]/div[1]/section[1]/div[1]/div[2]/div[3]/button[1]',
'/div[1]/div[1]/div[1]/section[1]/div[1]/div[2]/div[3]/button[1]',
'/div[2]/div[1]/div[1]/div[1]/section[1]/div[1]/div[2]/div[3]/button[1]',
'/div[1]/div[2]/div[1]/div[1]/div[1]/section[1]/div[1]/div[2]/div[3]/button[1]',
'/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/section[1]/div[1]/div[2]/div[3]/button[1]',
'/div[2]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/section[1]/div[1]/div[2]/div[3]/button[1]',
'/div[3]/div[2]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/section[1]/div[1]/div[2]/div[3]/button[1]',
'/div[2]/div[3]/div[2]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/section[1]/div[1]/div[2]/div[3]/button[1]',
'/main[1]/div[2]/div[3]/div[2]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/section[1]/div[1]/div[2]/div[3]/button[1]',
'/body/main[1]/div[2]/div[3]/div[2]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/section[1]/div[1]/div[2]/div[3]/button[1]',
'/button[contains(@class, "show-more-click")]',
'//*[contains(@data-testid, "see-more")]',
'/button[contains(@data-testid, "see-more")]',
'//*[@data-testid="see-more"]',
'/button[@data-testid="see-more"]',
'//*[contains(@aria-label, "Cerrar")]',
'/button[contains(@aria-label, "Cerrar")]',
'//*[@aria-label="Cerrar"]',
'/button[@aria-label="Cerrar"]',
'/button[contains(@role, "button")]',
'/button[@role="button"]',
'//*[contains(@hierarchy, "transparent")]',
'/button[contains(@hierarchy, "transparent")]',
'//*[@hierarchy]',
'/button[@hierarchy]',
'//*[@hierarchy="transparent"]',
'/button[@hierarchy="transparent"]',
'//*[@id="reviews_capability_v3"]/div[1]/section[1]/div[1]/div[2]/div[3]/button[1]',
'//*[@id="reviews_capability_v3"]/div/section/div/div/div/button[1]'
]


xpath2 = [
    '//section/div/div/div',
    '//div/section/div/div/div',
    '//div/div/section/div/div/div',
    '//div/div/div/section/div/div/div',
    '//div/div/div/div/section/div/div/div',
    '//div/div/div/div/div/section/div/div/div',
    '//div/div/div/div/div/div/section/div/div/div',
    '//div/div/div/div/div/div/div/section/div/div/div',
    '//div/div/div/div/div/div/div/div/section/div/div/div',
    '//main/div/div/div/div/div/div/div/div/div/section/div/div/div',
    '//body/main/div/div/div/div/div/div/div/div/div/div/section/div/div/div',
    '//div[contains(@class, "ui-review-capability-filter")]',
    '//*[contains(@data-testid, "filter-component")]',
    '//div[contains(@data-testid, "filter-component")]',
    '//*[@data-testid="filter-component"]',
    '//div[@data-testid="filter-component"]',
    '//*[@id="reviews_capability_v3"]/div/section/div/div/div',
    '//*[@id="reviews_capability_v3"]/div/section/div/div/div'
]
